name: Clone other repo

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    workflow_dispatch:

jobs:
    gen-doxyfile:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Checkout
            uses: actions/checkout@v3
            with:
              repository: asabon/Document
              path: document

          - name: Check list
            run: |
              pwd
              ls
