name: Clone other repo

on:
    push:
      paths:
        - .github/workflows/clone-other-repo.yml
    workflow_dispatch:

jobs:
    clone-other-reposigory:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout current repository
            uses: actions/checkout@v3

          - name: Checkout other repository
            uses: actions/checkout@v3
            with:
              repository: asabon/Documents
              path: documents

          - run: |
              cd
              pwd
              ls
