name: Clone other repository

on:
    push:
      paths:
        - .github/workflows/clone-other-repo.yml
    workflow_dispatch:

jobs:
    clone-other-reposigory:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout current repository
            uses: actions/checkout@v3
            with:
              path: work

          - name: Checkout other repository
            uses: actions/checkout@v3
            with:
              repository: asabon/Sandbox
              path: sandbox

          - run: mkdir -p sandbox/work
          - run: cp work/sample.md sandbox/work/

          - run: |
              cd sandbox
              git add -A
              if ! git diff --cached --quiet; then
                git config --local user.email "github-actions@github.com"
                git config --local user.name "github-actions"
                echo "commit"
                git commit -m "deploy"
                echo "pull"
                git pull origin main
                echo "push"
                git push origin main
              fi
          
          - run: |
              cd sandbox/work
              ls
