name: Clone other repository

on:
    push:
      paths:
        - .github/workflows/clone-other-repo.yml
    workflow_dispatch:

jobs:
    clone-other-reposigory:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout current repository
            uses: actions/checkout@v3
            with:
              path: work
          - name: Checkout other repository
            uses: actions/checkout@v3
            with:
              repository: asabon/Sandbox
              path: sandbox

          - run: mkdir -p sandbox/work
          - run: cp work/sample.md sandbox/work/

          - run: |
              cd sandbox
              git add -A
              if ! git diff --cached --quiet; then
                git commit -m "deploy"
                git pull
                git push origin master
              fi

          - run: |
              cd sandbox/work
              ls
