name: Push to other repository

on:
    push:
      paths:
        - .github/workflows/push-to-other-repo.yml
    workflow_dispatch:

jobs:
    push-to-other-reposigory:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout current repository
            uses: actions/checkout@v3
            with:
              path: work

          - name: Checkout other repository
            uses: actions/checkout@v3
            with:
              repository: asabon/Sandbox
              path: sandbox
              ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

          - run: mkdir -p sandbox/work
          - run: cp work/sample.md sandbox/work/

          - name: Deploy
            env:
              GH_TOKEN: ${{ github.token }}
            run: |
              cd sandbox
              echo "add"
              git add -A
              if ! git diff --cached --quiet; then
                echo "== git config =="
                git config --local user.email "github-actions@github.com"
                git config --local user.name "github-actions"
                echo "== git commit =="
                git commit -m "deploy"
                echo "== git pull origin main =="
                git pull origin main
                echo "== gh ssh-key list =="
                gh ssh-key list
                echo "== gh repo deploy-key list =="
                gh repo deploy-key list
                echo "== gh repo list =="
                gh repo list asabon
                echo "== gh repo view =="
                gh repo view
              fi
          
          - run: |
              cd sandbox/work
              ls
