name: Push to other repository

on:
    push:
      paths:
        - .github/workflows/push-to-other-repo.yml
    workflow_dispatch:

jobs:
    push-to-other-reposigory:
        runs-on: ubuntu-latest
    
        steps:
          # Check out source repository
          - name: Checkout current repository
            uses: actions/checkout@v3
            with:
              path: work

          # Check out destination repository
          - name: Checkout other repository
            uses: actions/checkout@v3
            with:
              repository: asabon/Sandbox
              path: sandbox

          - run: mkdir -p sandbox/work
          - run: cp work/sample.md sandbox/work/

#          - run: ssh-add -l -E sha256

          - name: Setup
            run: |
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/deploy_key.pem
              chmod 600 ~/deploy_key.pem
              ssh-add ~/deploy_key.pem

#          - run: ssh-add -l -E sha256

#          - run: ssh -vT git@github.com

#          - run: ssh -T git@github.com

          - name: Deploy
            run: |
              cd sandbox
              echo "add"
              git add -A
              if ! git diff --cached --quiet; then
                echo "config"
                git config --local user.email "github-actions@github.com"
                git config --local user.name "github-actions"
                echo "commit"
                git commit -m "deploy"
                echo "pull"
                git pull origin main
                gh repo sync
              fi
          
          - run: |
              cd sandbox/work
              ls
