name: ssh-keygen

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Key name'
        required: false
        default: 'id_rsa'
      type:
        description: 'Type'
        required: false
        default: 'rsa'
      bit:
        description: 'Bit num'
        required: false
        default: '4096'

jobs:
  ssh-keygen:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keys
        run: ssh-keygen -f ${{ inputs.name }} -t ${{ inputs.type }} -b ${{ inputs.bit }}

      - run: ls
      - run: ls ~/

      - name: Upload generated keys
        uses: actions/upload-artifact@v3
        with:
          name: ssh-keypair
          path: ~/.ssh
